line-length = 120
target-version = "py310"

# ノイズを減らすため、重いテスト用スキャフォールディングのディレクトリを lint 対象から除外
exclude = [
  "tests/**",
  ".venv/**",
  "**/site-packages/**",
]


[lint]
select = [
  "E",  # pycodestyle のエラー（E402: ファイル先頭での import を含む）
  "F",  # pyflakes
  "I",  # isort（インポートの並べ替え）
  "C901", # 関数の複雑度
  "PLR0912", # 分岐数
  "PLR0915", # ステートメント数
]
ignore = []

[lint.per-file-ignores]
# 統合テストファイルはカバレッジ用スキャフォールディングとして
# 多数のヘルパー import と未使用変数を意図的に含むため、
# 雑多な失敗を避ける目的で一部の規則を緩和する。
"test_xlsx2json.py" = [
  "F401", # インポートされたが未使用
  "F841", # 代入されたが未使用
  "I001", # インポートブロックが未ソート/未整形（大きな単一ファイル）
  "E501", # 行が長すぎる
  "E711", # None の比較スタイル
  "E712", # True/False の直接比較
  "E741", # 曖昧な変数名
  "C901", # テスト用ヘルパー関数は複雑になり得る
  "PLR0912", # 大型テストケースで分岐が多い
  "PLR0915", # 大型テストケースでステートメントが多い
  "E702", # テストデータ準備で 1 行に複数ステートメント
]

# 大きな単一ソースファイルでは、インポートや一時変数に関する厳格なスタイルよりも安定性を優先
"xlsx2json.py" = [
  "I001", # インポートブロックが未ソート/未整形
  "E501", # 行が長すぎる（大きなコメント/ドックストリングは許容）
  "F401", # インポートされたが未使用（機能フラグによるオプション import を含む）
  "F841", # 代入されたが未使用（デバッグ用フックのため保持）
  "E402", # 単一ファイルの事情により先頭以外での import を許可
  "C901", # 複雑度は一時的に無視（段階的に削減予定）
  "PLR0912", # 分岐の多さは一時的に無視
]

# ユニットの小規模テストは意図的な import 順序や未使用がある
"test_unit_small.py" = [
  "I001",
  "F401",
]

[lint.pylint]
max-statements = 60

[format]
quote-style = "preserve"
indent-style = "space"
